# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/display.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(826, 455)
        MainWindow.setMaximumSize(QtCore.QSize(1400, 1050))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphic_wappen_heim = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphic_wappen_heim.setEnabled(True)
        self.graphic_wappen_heim.setGeometry(QtCore.QRect(10, 10, 308, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphic_wappen_heim.sizePolicy().hasHeightForWidth())
        self.graphic_wappen_heim.setSizePolicy(sizePolicy)
        self.graphic_wappen_heim.setObjectName("graphic_wappen_heim")
        self.graphic_wappen_gast = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphic_wappen_gast.setGeometry(QtCore.QRect(510, 10, 307, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphic_wappen_gast.sizePolicy().hasHeightForWidth())
        self.graphic_wappen_gast.setSizePolicy(sizePolicy)
        self.graphic_wappen_gast.setObjectName("graphic_wappen_gast")
        self.label_versus = QtWidgets.QLabel(self.centralwidget)
        self.label_versus.setGeometry(QtCore.QRect(324, 12, 181, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_versus.sizePolicy().hasHeightForWidth())
        self.label_versus.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_versus.setFont(font)
        self.label_versus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_versus.setObjectName("label_versus")
        self.label_spielstand_doppelpunkt = QtWidgets.QLabel(self.centralwidget)
        self.label_spielstand_doppelpunkt.setGeometry(QtCore.QRect(319, 242, 191, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_spielstand_doppelpunkt.sizePolicy().hasHeightForWidth())
        self.label_spielstand_doppelpunkt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_spielstand_doppelpunkt.setFont(font)
        self.label_spielstand_doppelpunkt.setLineWidth(0)
        self.label_spielstand_doppelpunkt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spielstand_doppelpunkt.setObjectName("label_spielstand_doppelpunkt")
        self.label_spielstand_heim = QtWidgets.QLabel(self.centralwidget)
        self.label_spielstand_heim.setGeometry(QtCore.QRect(10, 250, 308, 132))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_spielstand_heim.sizePolicy().hasHeightForWidth())
        self.label_spielstand_heim.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_spielstand_heim.setFont(font)
        self.label_spielstand_heim.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spielstand_heim.setObjectName("label_spielstand_heim")
        self.label_spielstand_gast = QtWidgets.QLabel(self.centralwidget)
        self.label_spielstand_gast.setGeometry(QtCore.QRect(510, 250, 301, 132))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_spielstand_gast.sizePolicy().hasHeightForWidth())
        self.label_spielstand_gast.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_spielstand_gast.setFont(font)
        self.label_spielstand_gast.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spielstand_gast.setObjectName("label_spielstand_gast")
        self.label_time = QtWidgets.QLabel(self.centralwidget)
        self.label_time.setGeometry(QtCore.QRect(320, 390, 191, 33))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time.sizePolicy().hasHeightForWidth())
        self.label_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_time.setFont(font)
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SCK Anzeigetafel"))
        self.label_versus.setText(_translate("MainWindow", "-"))
        self.label_spielstand_doppelpunkt.setText(_translate("MainWindow", ":"))
        self.label_spielstand_heim.setText(_translate("MainWindow", "0"))
        self.label_spielstand_gast.setText(_translate("MainWindow", "0"))
        self.label_time.setText(_translate("MainWindow", "00:00"))
    
if __name__ == "__main__":
    from PyQt5 import QtWidgets


    class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
        def __init__(self):
            super().__init__()
            self.setupUi(self)


    import sys

    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    w.show()
    app.exec_()
    