# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/display.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Display(object):
    def setupUi(self, Display):
        Display.setObjectName("Display")
        Display.setEnabled(True)
        Display.resize(192, 128)
        Display.setMaximumSize(QtCore.QSize(1400, 1050))
        self.graphic_wappen_heim = QtWidgets.QGraphicsView(Display)
        self.graphic_wappen_heim.setEnabled(True)
        self.graphic_wappen_heim.setGeometry(QtCore.QRect(10, 10, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphic_wappen_heim.sizePolicy().hasHeightForWidth())
        self.graphic_wappen_heim.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(False)
        self.graphic_wappen_heim.setFont(font)
        self.graphic_wappen_heim.setAcceptDrops(False)
        self.graphic_wappen_heim.setToolTip("")
        self.graphic_wappen_heim.setStatusTip("")
        self.graphic_wappen_heim.setWhatsThis("")
        self.graphic_wappen_heim.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphic_wappen_heim.setObjectName("graphic_wappen_heim")
        self.label_spielstand_gast = QtWidgets.QLabel(Display)
        self.label_spielstand_gast.setGeometry(QtCore.QRect(130, 60, 51, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_spielstand_gast.sizePolicy().hasHeightForWidth())
        self.label_spielstand_gast.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_spielstand_gast.setFont(font)
        self.label_spielstand_gast.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spielstand_gast.setObjectName("label_spielstand_gast")
        self.graphic_wappen_gast = QtWidgets.QGraphicsView(Display)
        self.graphic_wappen_gast.setGeometry(QtCore.QRect(130, 10, 50, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphic_wappen_gast.sizePolicy().hasHeightForWidth())
        self.graphic_wappen_gast.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setKerning(False)
        self.graphic_wappen_gast.setFont(font)
        self.graphic_wappen_gast.setAcceptDrops(False)
        self.graphic_wappen_gast.setToolTip("")
        self.graphic_wappen_gast.setStatusTip("")
        self.graphic_wappen_gast.setWhatsThis("")
        self.graphic_wappen_gast.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphic_wappen_gast.setObjectName("graphic_wappen_gast")
        self.label_spielstand_doppelpunkt = QtWidgets.QLabel(Display)
        self.label_spielstand_doppelpunkt.setGeometry(QtCore.QRect(60, 60, 71, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_spielstand_doppelpunkt.sizePolicy().hasHeightForWidth())
        self.label_spielstand_doppelpunkt.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_spielstand_doppelpunkt.setFont(font)
        self.label_spielstand_doppelpunkt.setLineWidth(0)
        self.label_spielstand_doppelpunkt.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spielstand_doppelpunkt.setObjectName("label_spielstand_doppelpunkt")
        self.label_time = QtWidgets.QLabel(Display)
        self.label_time.setGeometry(QtCore.QRect(10, 90, 171, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time.sizePolicy().hasHeightForWidth())
        self.label_time.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time.setFont(font)
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.label_spielstand_heim = QtWidgets.QLabel(Display)
        self.label_spielstand_heim.setGeometry(QtCore.QRect(10, 60, 51, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_spielstand_heim.sizePolicy().hasHeightForWidth())
        self.label_spielstand_heim.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_spielstand_heim.setFont(font)
        self.label_spielstand_heim.setAlignment(QtCore.Qt.AlignCenter)
        self.label_spielstand_heim.setObjectName("label_spielstand_heim")

        self.retranslateUi(Display)
        QtCore.QMetaObject.connectSlotsByName(Display)

    def retranslateUi(self, Display):
        _translate = QtCore.QCoreApplication.translate
        Display.setWindowTitle(_translate("Display", "SCK Anzeigetafel"))
        self.label_spielstand_gast.setText(_translate("Display", "0"))
        self.label_spielstand_doppelpunkt.setText(_translate("Display", ":"))
        self.label_time.setText(_translate("Display", "00:00"))
        self.label_spielstand_heim.setText(_translate("Display", "0"))
    
if __name__ == "__main__":
    from PyQt5 import QtWidgets


    class MainWindow(QtWidgets.QMainWindow, Ui_MainWindow):
        def __init__(self):
            super().__init__()
            self.setupUi(self)


    import sys

    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    w.show()
    app.exec_()
    